[workspace]
members = ["server", "worker"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "./README.md"

[workspace.dependencies]
serde = "1.0.197"
serde_json = "1.0.115"

aws-config = { version = "1.2.0", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.22.0"

chrono-tz = "0.9.0"
chrono = { version = "0.4.37", features = ["serde"] }

thiserror = "1.0.58"

[profile.release]
lto = true
strip = true
codegen-units = 1
