name: Server workflow

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/workflow_server.yaml"
      - ".github/workflows/build_server.yaml"
      - "server/src/**"
      - "server/Cargo.toml"
      - "server/Cargo.lock"
      - "server/Dockerfile"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  quality:
    name: Quality Checks for Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --package server --all --check

      - name: Lint
        run: cargo clippy --package server --all-targets --all-features -- -D warnings

      - name: Lint
        run: cargo test --package server

      - name: Audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: "Build"
    needs: quality
    uses: ./.github/workflows/build_server.yaml
    secrets: inherit

  deploy:
    if: ${{ github.ref_name == 'main' }}
    name: Update ECS instances with new image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }}  --service ${{ secrets.ECS_SERVICE }} --force-new-deployment
