name: Server workflow

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/workflow_server.yaml"
      - ".github/workflows/build_server.yaml"
      - "server/src/**"
      - "server/Cargo.toml"
      - "server/Cargo.lock"
      - "server/Dockerfile"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  quality:
    name: Quality Checks for Server
    uses: ./.github/workflows/_quality_checks.yaml
    with:
      package: waterheater-calc

  build:
    name: "Build"
    needs: quality
    secrets: inherit
    uses: ./.github/workflows/build_server.yaml

  deploy:
    if: ${{ github.ref_name == 'main' }}
    name: Redeploy AWS App Runner service
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Start App Runner deployment with AWS CLI
        run: |
          aws apprunner start-deployment --service-arn ${{ secrets.AWS_APP_RUNNER_ARN }}
