name: Server workflow

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/workflow_server.yaml"
      - "server/lambda-infra/**"
      - "server/src/**"
      - "server/Cargo.toml"
      - "server/Cargo.lock"
      - "server/Dockerfile"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  quality:
    name: Quality Checks for Server
    uses: ./.github/workflows/_quality_checks.yaml
    with:
      package: waterheater-calc

  quality_infra:
    name: Quality Checks for server infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install
        working-directory: ./server/lambda-infra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache

      - name: Build Worker
        run: |
          pip install cargo-lambda
          cargo lambda build --package waterheater-calc --release

      - uses: pulumi/actions@v5
      - run: |
          pulumi stack select server-lambda
          pulumi preview
        working-directory: ./server/lambda-infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy_infra:
    needs: quality_infra
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install
        working-directory: ./server/lambda-infra

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: waterheater-calc-cache

      - name: Build Worker
        run: |
          pip install cargo-lambda
          cargo lambda build --package waterheater-calc --release

      - uses: pulumi/actions@v5
      - run: |
          pulumi stack select server-lambda
          pulumi up --skip-preview
        working-directory: ./server/lambda-infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
